project:
  type: website
  resources:
    - manifest.json

website:
  title: "Posit Team Dedicated"
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - team.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly

execute:
  freeze: auto

