name: lib

on:
  push:
    branches: [main]
    tags: [v*]
    paths: [lib/**,.github/workflows/lib.yml]

  pull_request:
    paths: [lib/**,.github/workflows/lib.yml]

  merge_group:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: extractions/setup-just@v2

      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y libgpgme-dev libbtrfs-dev

      - uses: actions/setup-go@v5
        with:
          go-version-file: lib/go.mod
          cache: true
          cache-dependency-path: |
            lib/go.sum

      - name: Test lib with coverage
        run: just test-lib
